### ISSUE TITLE
Really, Big GURLS?

### ISSUE THREAD

**Issue by poulson** [LCSL/GURLS#19]
This project looks very well done, but it is unfortunate that in 2015 that an academic group would choose to name the large-scale version Big GURLS. Might I humbly suggest changing this?

**Comment by jseabold** [comment]
Agreed.

**Comment by gevangel** [comment]
Thanks for the comments. We agree and it goes without saying that any connotations with the library name are unfortunate and obviously very far from being intended. For that reason, a change in the library name is in our immediate plans for one of the upcoming versions/releases.
