### ISSUE TITLE
scikits-learn

### ISSUE THREAD

**Issue by ardila** [LCSL/GURLS#6]
Are there any plans to contribute this project to scikits-learn?

**Comment by gevangel** [comment]
Long overdue response :) but here goes in case it is of any use: For the time being this is an independent project/library with support for C++ and MATLAB. There is a recent Python wrapper for GURLS++ written in Cython and integrated with NumPy that we plan to integrate to the main repository at some point. See here: [https://github.com/phrqas/GURLS] for the preliminary version and a number of benchmarks with respect to scikit-learn.
